name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - run: make push
